# Generated by Django 5.2 on 2026-09-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Campus Main Battery', help_text='Identifier for the battery unit', max_length=120)),
                ('capacity_kwh', models.FloatField(default=220.0, help_text='Total energy storage capacity in kWh')),
                ('initial_energy_kwh', models.FloatField(default=110.0, help_text='Starting energy at hour 0 in kWh')),
                ('minimum_energy_kwh', models.FloatField(default=40.0, help_text='Baseline reserve threshold in kWh')),
                ('max_charge_kwh_per_hour', models.FloatField(default=50.0, help_text='Max charge speed per hour')),
                ('max_discharge_kwh_per_hour', models.FloatField(default=50.0, help_text='Max discharge speed per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Battery Configuration',
                'verbose_name_plural': 'Battery Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.CharField(db_index=True, max_length=255)),
                ('total_grid_kwh', models.FloatField(default=0.0, verbose_name='Total Grid Import (kWh)')),
                ('total_cost_bdt', models.FloatField(default=0.0, verbose_name='Total Cost (BDT)')),
                ('peak_grid_kwh', models.FloatField(default=0.0, verbose_name='Peak Grid Draw (kWh)')),
                ('plan_summary', models.TextField(blank=True, default='')),
                ('battery_capacity_kwh', models.FloatField(blank=True, null=True)),
                ('raw_operator_notes', models.JSONField(blank=True, default=list, help_text='Input operator notes list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Optimization Scenario',
                'verbose_name_plural': 'Optimization Scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_index', models.IntegerField(default=0)),
                ('raw_note', models.TextField(blank=True, default='')),
                ('applies', models.BooleanField(default=False)),
                ('directive_type', models.CharField(max_length=50)),
                ('structured_adjustment', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='energy.optimizationscenario')),
            ],
            options={
                'verbose_name': 'Directive Interpretation',
                'verbose_name_plural': 'Directive Interpretations',
                'ordering': ['scenario', 'note_index'],
            },
        ),
        migrations.CreateModel(
            name='HourlyPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(verbose_name='Hour of Day (0-23)')),
                ('grid_kwh', models.FloatField(default=0.0, verbose_name='Grid Import (kWh)')),
                ('solar_used_kwh', models.FloatField(default=0.0, verbose_name='Solar Energy Used (kWh)')),
                ('battery_action', models.CharField(choices=[('charge', 'Charge'), ('discharge', 'Discharge'), ('idle', 'Idle')], default='idle', max_length=20)),
                ('battery_kwh', models.FloatField(default=0.0, verbose_name='Battery Charged / Discharged (kWh)')),
                ('battery_energy_after_kwh', models.FloatField(default=0.0, verbose_name='Battery State of Charge (kWh)')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_plans', to='energy.optimizationscenario')),
            ],
            options={
                'verbose_name': 'Hourly Plan Entry',
                'verbose_name_plural': 'Hourly Plan Entries',
                'ordering': ['scenario', 'hour'],
                'unique_together': {('scenario', 'hour')},
            },
        ),
    ]
